### ISSUE TITLE
video_primary/video_fga adaptation set IDs?

### ISSUE THREAD

**Issue by roman380** [ZmGorynych/L3D#1]
https://github.com/ZmGorynych/L3D/blob/43d21c57b828082697b09dd6ff3010e6f0a33ddc/l3d_low_delay_example.mpd#L32C24-L32C37

I suppose there is aone or a few copy/paste problems around adaptation set ID.

The second set id should be `video_fga`, right, and then the two cross-reference one another?

**Comment by ZmGorynych** [comment]
Fixed
