### ISSUE TITLE
Space separated vs. comma separated

### ISSUE THREAD

**Issue by roman380** [ZmGorynych/L3D#2]
https://github.com/ZmGorynych/L3D/blob/43d21c57b828082697b09dd6ff3010e6f0a33ddc/l3d_low_delay_example.mpd#L33C73-L33C86

I know it's a spec Q, not an example Q, but why `urn:mpeg:dash:ssr:2023` list is space separated when values for `urn:mpeg:dash:adaptation-set-switching:2016` lists are defined as comma separated?

**Comment by ZmGorynych** [comment]
XML list is space-separated. At some point people missed this in their contributions. Probably needs fixing.
